### ISSUE TITLE
ImportError: No module named progressbar

### ISSUE THREAD

**Issue by muhsinsaral** [andresaraque/centauri6dof#2]
Hi, I am trying to run "rosrun rqt_mypkg rqt_mypkg" and I get the following error.

```
srl@srl-X550VX:~/catkin_ws$ rosrun rqt_mypkg rqt_mypkg
Traceback (most recent call last):
  File "/home/srl/catkin_ws/src/centauri6dof-master/rqt_mypkg/scripts/rqt_mypkg", line 5, in <module>
    from rqt_mypkg.my_module import MyPlugin
  File "/home/srl/catkin_ws/src/centauri6dof-master/rqt_mypkg/src/rqt_mypkg/my_module.py", line 23, in <module>
    from progressbar import ProgressBar
ImportError: No module named progressbar
```

**Comment by muhsinsaral** [comment]
`sudo` apt-get install python-progressbar` solved my problem.

**Comment by muhsinsaral** [comment]
`sudo apt-get install python-progressbar` solved my problem
